version: "0.2"
language: en-GB
words:
  - ahash
  - appendleft
  - arange
  - argmax
  - astype
  - atran
  - autoupdate
  - azurecr
  - azured
  - bbox
  - bitfields
  - Bitmask
  - blockxsize
  - blockysize
  - boto
  - botocore
  - boundscheck
  - caplog
  - capsys
  - cdef
  - cdist
  - cdylib
  - certifi
  - chunksize
  - cimport
  - cleanup
  - cmap
  - cmdclass
  - cobertura
  - Cobertura
  - codegen
  - colorbar
  - coveragerc
  - cpdef
  - cpython
  - cython
  - cythonize
  - dask
  - dataframe
  - datetimez
  - defaultdict
  - Deque
  - Docstyle
  - dotenv
  - dropna
  - dtype
  - EDEM
  - edgecolor
  - einops
  - elif
  - emis
  - emsd
  - epsg
  - EPSG
  - errmsg
  - errorfactory
  - extern
  - facecolor
  - figsize
  - fillna
  - GDAL
  - geopandas
  - georeferenced
  - geotiff
  - getattr
  - getpid
  - getsizeof
  - Hadoop
  - hashbrown
  - hashkey
  - Huadu
  - idxmin
  - iloc
  - imshow
  - inplace
  - ipykernel
  - ipynb
  - ipython
  - isin
  - isna
  - Isort
  - istio
  - junitxml
  - jupyter
  - justfile
  - kubeflow
  - landclass
  - landsat
  - latlon
  - LDCM
  - levelname
  - libc
  - libexpat
  - lineprecision
  - linewidth
  - lowres
  - lwir
  - malloc
  - manylinux
  - maxx
  - maxy
  - mccabe
  - memray
  - memset
  - mininterval
  - miniters
  - miniterval
  - miny
  - MSVC
  - mypy
  - nanmax
  - nanmin
  - naturalearth
  - nbstripout
  - ncols
  - ndarray
  - ndvi
  - nogil
  - ntid
  - numpy
  - nums
  - opencv
  - openssl
  - orthorectified
  - osops
  - Perflint
  - popleft
  - Postgresql
  - postprocess
  - psutil
  - pycache
  - pyclass
  - pycodestyle
  - pydantic
  - pydocstyle
  - pyenv
  - pyfunction
  - pylance
  - Pylint
  - pymethods
  - pymodule
  - pyobject
  - pyproject
  - pystac
  - pytest
  - pythonpath
  - PYTHONPATH
  - pytorch
  - radiometrically
  - rasterio
  - readall
  - readline
  - rechunking
  - reexport
  - referer
  - rioxarray
  - rpath
  - RUSTFLAGS
  - secretkey
  - secretname
  - setdefault
  - setuptools
  - shapefile
  - shortwave
  - skipif
  - skipna
  - Soduku
  - softmax
  - ssize
  - stac
  - STAC
  - stackstac
  - stddev
  - stdlib
  - strs
  - Subarray
  - swarth
  - swir
  - teardown
  - toolz
  - torchserve
  - torchvision
  - tqdm
  - tryceratops
  - urad
  - urllib
  - USGS
  - venv
  - viridis
  - virtualenv
  - virtualenvs
  - VIRTUALENVS
  - watchexec
  - winge
  - winget
  - xarray
  - xlim
  - ylim
  - zarr
  - zlevel
  - ZSTD
