# [project]
# name = "cython_lib"
# version = "0.1.0"
# requires-python = ">=3.12"

[build-system]
requires = ["Cython>=3.0", "setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

# [tool.setuptools]
# packages = { find = { where = ["cython_lib"] } }
