from typing import Any

class MedianFinder:
    def __init__(self) -> None: ...
    def add_num(self, num: int) -> None: ...
    def find_median(self) -> float: ...

def can_complete_circuit(*args: Any, **kwargs: Any) -> Any: ...
def ways_of_change(coins: list[int], amount: int) -> int: ...
def missing_number(*args: Any, **kwargs: Any) -> Any: ...
def find_min(*args: Any, **kwargs: Any) -> Any: ...
def search(*args: Any, **kwargs: Any) -> Any: ...
def find_peak_element(*args: Any, **kwargs: Any) -> Any: ...
def k_closest(*args: Any, **kwargs: Any) -> Any: ...
def smallest_range(*args: Any, **kwargs: Any) -> Any: ...
def three_sum(*args: Any, **kwargs: Any) -> Any: ...
def two_sum_k(*args: Any, **kwargs: Any) -> Any: ...
def two_sum(*args: Any, **kwargs: Any) -> Any: ...
def window_maxes(*args: Any, **kwargs: Any) -> Any: ...
def sliding_window_median(*args: Any, **kwargs: Any) -> Any: ...
def range_addition(*args: Any, **kwargs: Any) -> Any: ...
def subarray_div_by_k(*args: Any, **kwargs: Any) -> Any: ...
def subarray_sum(*args: Any, **kwargs: Any) -> Any: ...
def longest_consecutive_sequence(*args: Any, **kwargs: Any) -> Any: ...
def longest_sum_within_k(*args: Any, **kwargs: Any) -> Any: ...
def max_area(*args: Any, **kwargs: Any) -> Any: ...
def largest_area_rectangle(*args: Any, **kwargs: Any) -> Any: ...
def max_product(*args: Any, **kwargs: Any) -> Any: ...
def min_sub_array_len(*args: Any, **kwargs: Any) -> Any: ...
def product_except_self(*args: Any, **kwargs: Any) -> Any: ...
def find_shortest_subarray_to_remove(*args: Any, **kwargs: Any) -> Any: ...
def total_patch(*args: Any, **kwargs: Any) -> Any: ...
def can_be_grouped(*args: Any, **kwargs: Any) -> Any: ...
def max_min_gap(*args: Any, **kwargs: Any) -> Any: ...
def longest_increasing_subsequence(nums: list[int]) -> int: ...
def min_jump(*args: Any, **kwargs: Any) -> Any: ...
def increasing_triplet(*args: Any, **kwargs: Any) -> Any: ...
def count_triplets(*args: Any, **kwargs: Any) -> Any: ...

