from typing import Any

def generate_parentheses(*args: Any, **kwargs: Any) -> Any: ...
def validate_parenthesis(*args: Any, **kwargs: Any) -> Any: ...
def group_anagrams(*args: Any, **kwargs: Any) -> Any: ...
def num_ways(*args: Any, **kwargs: Any) -> Any: ...
def partition_lengths(*args: Any, **kwargs: Any) -> Any: ...
def ways_of_decoding(*args: Any, **kwargs: Any) -> Any: ...
def num_splits(*args: Any, **kwargs: Any) -> Any: ...
def word_break(*args: Any, **kwargs: Any) -> Any: ...
def longest_common_subsequence(*args: Any, **kwargs: Any) -> Any: ...
def num_match_subsequences(*args: Any, **kwargs: Any) -> Any: ...
def check_inclusion(*args: Any, **kwargs: Any) -> Any: ...
def char_replacement(*args: Any, **kwargs: Any) -> Any: ...
def longest_palindrome(*args: Any, **kwargs: Any) -> Any: ...
def length_of_longest_substring(*args: Any, **kwargs: Any) -> Any: ...

