[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust"
crate-type = ["cdylib"]

[dependencies]
ahash = "0.8.12"
pyo3 = { version = "0.25", features = ["extension-module"] }

[profile.release]
lto = true
codegen-units = 1
